version: '3.7'

services:
  charting:
    container_name: charting
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
      - 9229:9229
    volumes:
      - ./src:/usr/src/app/src
