version: '3'

services:
  charting:
    container_name: charting
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    volumes:
      - ./src:/app/src
      - ./example:/app/example
      - ./scripts:/app/scripts
      - ./dist:/app/dist
