mkdir -p example/js/
cp node_modules/lodash/lodash.js example/js
cp node_modules/jquery/dist/jquery.min.js example/js
cp node_modules/d3/d3.min.js example/js
cp mapdc.min.css example/css/
cp chart.min.css example/css/
cp mapdc.js example/js/
cp ../mapd-crossfilter/mapd-crossfilter.js example/js/
cp ../mapd-con/thrift/browser/thrift.js example/js/
cp ../mapd-con/thrift/browser/mapd.thrift.js example/js/
cp ../mapd-con/thrift/browser/mapd_types.js example/js/
cp ../mapd-con/dist/MapdCon.js example/js/
cp ../mapd-mapbox-gl-js/dist/mapbox-gl.js example/js/
cp ../mapd-mapbox-gl-js/dist/mapboxgl-overrides.js example/js/
